<%= ENV['RAILS_ENV'] %>:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DATABASE_POOL_SIZE'] %>
  timeout: <%= ENV['DATABASE_TIMEOUT'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: '<%= File.read(ENV['DATABASE_PASSWORD_FILE']).chomp %>'
